// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfpyS0vOKDTK2UFTWn4wCFIUqZdFxjoJk',
    appId: '1:1072286631212:web:0ad6a566dc50c87e721889',
    messagingSenderId: '1072286631212',
    projectId: 'dalilyapp-5f5d3',
    authDomain: 'dalilyapp-5f5d3.firebaseapp.com',
    storageBucket: 'dalilyapp-5f5d3.firebasestorage.app',
    measurementId: 'G-P0FLL2WJ1S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZnFOxBQXGByCdRk1_tn9KowdCfvAch2Y',
    appId: '1:1072286631212:android:a7625b432fde25fa721889',
    messagingSenderId: '1072286631212',
    projectId: 'dalilyapp-5f5d3',
    storageBucket: 'dalilyapp-5f5d3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh5gOEgKSFWYeNkkKNH-lOgVpxShHezSc',
    appId: '1:1072286631212:ios:d70dd53d00ebeb2b721889',
    messagingSenderId: '1072286631212',
    projectId: 'dalilyapp-5f5d3',
    storageBucket: 'dalilyapp-5f5d3.firebasestorage.app',
    iosBundleId: 'com.example.dalily',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCh5gOEgKSFWYeNkkKNH-lOgVpxShHezSc',
    appId: '1:1072286631212:ios:d70dd53d00ebeb2b721889',
    messagingSenderId: '1072286631212',
    projectId: 'dalilyapp-5f5d3',
    storageBucket: 'dalilyapp-5f5d3.firebasestorage.app',
    iosBundleId: 'com.example.dalily',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfpyS0vOKDTK2UFTWn4wCFIUqZdFxjoJk',
    appId: '1:1072286631212:web:24d8ee761b5b3049721889',
    messagingSenderId: '1072286631212',
    projectId: 'dalilyapp-5f5d3',
    authDomain: 'dalilyapp-5f5d3.firebaseapp.com',
    storageBucket: 'dalilyapp-5f5d3.firebasestorage.app',
    measurementId: 'G-H43RZG303J',
  );
}
